app/urls.py
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
    path('', views.BookIndexView.as_view(), name='index'),
    path('Detail/<int:pk>', views.BookDetailView.as_view(), name='detail'),
    path('Check/', views.CheckView.as_view(), name='check'),
    path('Mypage/', views.MypageView.as_view(), name='mypage'),
    path('Inquiry/', views.InquiryView.as_view(), name='inquiry'),
]

librarian/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('app.urls')),
]
# 画像を表示させる
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>{% block title %}Librarian{% endblock %}</title>
    {% load bootstrap4 %}
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
    {% block extra_head %}{% endblock %}
</head>
<style>

    header {
        display: flex;
        justify-content: space-between;
        height: 80px;
        box-shadow: 0px 0px 5px 0px hsla(0, 0%, 7%, 0.3);
        padding: 0 20px 0;
        margin-bottom: 50px;
    }

    code {
        display: inline-block;
        padding: 0.1em 0.25em; /* 文字周りの余白 */
        color: #444; /* 文字色 */
        background-color: #e7edf3; /* 背景色 */
        border-radius: 3px; /* 角丸 */
        border: solid 1px #d6dde4; /* 枠線 */
    }

    h1 {
        font-size: 40px;
        font-weight: bold;
    }

    h2 {
        font-size: 25px;
        font-weight: bold;
    }

    h3 {
        font-size: 20px;
    }

    h4 {
        font-size: 16px;
    }
</style>

<body>

<header class="d-flex">
    <h1 class="d-flex align-items-center"><a href="{% url "app:index" %}" class="text-reset text-decoration-none">Librarian</a>
    </h1>
    {% if user.is_authenticated %}
        <div class="d-flex">
            <div class="d-flex align-items-center mr-3">
                <form action="{% url 'app:check' %}" method="POST">{% csrf_token %}
                    <input placeholder="ISBNコードを入力" type="text" name="isbn" required id="isbn_code">
                    <input type="submit" value="確認">
                </form>
            </div>
            <div class="d-flex align-items-center">
                <p class="m-3">
                <form action="{% url 'app:mypage' %}" method="post">{% csrf_token %}
                    <input class="submit" type="submit" value="{{ user.username }} さん">
                </form>
                </p>
                <div class="row my-3 mx-1">
                    <p class="m-1"><a href="{% url 'admin:index' %}">管理画面</a></p>
                    <p class="m-1"><a href="{% url 'logout' %}">ログアウト</a></p>
                </div>
            </div>
            {% else %}
            <p><a href="{% url 'login' %}">ログイン</a></p>
        </div>

        </div>

    {% endif %}
</header>
{% if user.is_authenticated %}
    <div class="container mt-3">
        <div class="messages">
            {% for message in messages %}
                <li class="alert{% if message.tags %} alert-{{ message.tags }}{% endif %} alert-dismissible"
                    role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    {{ message }}</li>
            {% endfor %}
        </div>
        {% block content %}
        {% endblock content %}

    </div>
{% else %}
    <div class="ml-4">ログインしてください。</div>
{% endif %}
</body>
</html>