app/urls.py
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
    path('', views.BookIndexView.as_view(), name='index'),
    path('Detail/<int:pk>', views.BookDetailView.as_view(), name='detail'),
    path('Check/', views.CheckView.as_view(), name='check'),
    path('Mypage/', views.MypageView.as_view(), name='mypage'),
    path('Inquiry/', views.InquiryView.as_view(), name='inquiry'),
]

librarian/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('app.urls')),
]
# 画像を表示させる
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models
from django.utils import timezone
import json, requests
import datetime
from user.models import User
from django.core.files import File
from imageio import imread
from tempfile import NamedTemporaryFile
from urllib.request import urlopen

# 現在の時刻を取得
now_time = datetime.datetime.now()


# 出版情報
class Publisher(models.Model):
    name = models.CharField(
        verbose_name='出版社名',
        max_length=50,
    )

    def __str__(self):
        return self.name


# 著者情報
class Author(models.Model):
    name = models.CharField(
        verbose_name='著者名',
        max_length=50,
    )
    a_detail = models.TextField(
        verbose_name='著者紹介',
        max_length=100,
        null=True, blank=True,
    )

    def __str__(self):
        return self.name


class Book(models.Model):
    isbn = models.CharField(
        verbose_name='ISBN',
        max_length=50,
    )
    rent = models.BooleanField(
        verbose_name='帯出区分',
        default=False,
    )
    title = models.CharField(
        verbose_name='書籍名',
        max_length=50,
        null=True, blank=True,
    )
    title2 = models.CharField(
        verbose_name='ショセキメイ',
        max_length=50,
        null=True, blank=True,
    )
    name = models.ForeignKey(
        Author, on_delete=models.CASCADE,
        verbose_name='著者名',
        null=True, blank=True,
    )

    book_img = models.CharField(
        verbose_name='画像リンク',
        max_length=100,
        null=True, blank=True,
    )
    publisher_name = models.ForeignKey(
        Publisher, on_delete=models.CASCADE,
        verbose_name='出版社',
        null=True, blank=True, )
    code = models.CharField(
        verbose_name='Cコード',
        max_length=100,
        null=True, blank=True,
    )
    time = models.CharField(
        verbose_name='出版日',
        max_length=10,
        null=True, blank=True,
    )
    page = models.IntegerField(
        verbose_name='ページ数',
        null=True, blank=True,
    )
    detail = models.TextField(
        verbose_name='内容',
        max_length=500,
        null=True, blank=True,
    )
    book_q = models.IntegerField(
        verbose_name='在庫数',
        blank=True,
        null=True,
        default=0,
    )
    save_image = models.ImageField(
        verbose_name='保存画像',
        upload_to='images',
        default='',
        blank=True,
        null=True,
    )

    def __str__(self):
        return self.isbn

    # # adminで画像表示させる
    # def admin_og_image(self):
    #     if self.save_image:
    #         return '<img src="{}" style="width:100px;height:auto;">'.format(self.save_image)
    #     else:
    #         return 'no image'
    #     admin_og_image.allow_tags = True

    def save(self, *args, **kwargs):
        # APIで本の情報を取得
        url = requests.get(f"https://api.openbd.jp/v1/get?isbn={self.isbn}&pretty")
        text = url.text
        data = json.loads(text)

        # 取得したjsonデータよりそれぞれの項目を取得する
        book = data[0]
        name_info = book['onix']['DescriptiveDetail']['TitleDetail']['TitleElement']['TitleText']
        book_name = name_info['content']
        book_name2 = name_info['collationkey']
        author = book['onix']['DescriptiveDetail']['Contributor'][0]['PersonName']['content']
        book_image = book['onix']['CollateralDetail']['SupportingResource'][0]['ResourceVersion'][0]['ResourceLink']
        publisher = book['summary']['publisher']

        c_code = book['onix']['DescriptiveDetail']['Subject'][0]['SubjectCode']
        syuppan_date = book['hanmoto']['dateshuppan']
        book_page = book['onix']['DescriptiveDetail']['Extent'][0]['ExtentValue']
        book_detail = book['onix']['CollateralDetail']['TextContent'][0]['Text']
        author_detail = book['onix']['DescriptiveDetail']['Contributor'][0]['BiographicalNote']

        # 出版社名が同じものがすでに保存されているか確認する
        p = Publisher.objects.filter(name=publisher)
        if p.count() < 1:
            Publisher(name=publisher).save()

        p = Publisher.objects.get(name=publisher)

        # 著者名が同じものがすでに保存されているか確認する
        a = Author.objects.filter(name=author)
        if a.count() < 1:
            Author(name=author, a_detail=author_detail).save()

        a = Author.objects.get(name=author)

        # p_name = [publisher.id for publisher in Publisher.objects.filter(name=publisher)][0]

        # 取得したデータをオーバーライド
        self.title = book_name
        self.title2 = book_name2
        self.name = a
        self.book_img = book_image
        self.publisher_name = p
        self.code = c_code
        self.time = syuppan_date
        self.page = book_page
        self.detail = book_detail

        # 画像をダウンロードして保存
        if self.book_img and not self.save_image:
            img_temp = NamedTemporaryFile(delete=True)
            img_temp.write(urlopen(book_image).read())
            img_temp.flush()
            self.save_image.save(f"image_{self.pk}.jpg", File(img_temp))

        super(Book, self).save(*args, **kwargs)




# 本の履歴情報
class BookHistory(models.Model):
    change = models.IntegerField(
        verbose_name='在庫変動数',
        default=0,
    )
    date = models.DateTimeField(
        verbose_name='日付',
        default=timezone.now,
        null=True, blank=True,
    )
    book = models.ForeignKey(
        Book, on_delete=models.CASCADE,
        verbose_name='ISBN',
        null=True, blank=True,
    )
    user = models.CharField(
        verbose_name='作業した人',
        max_length=50,
    )
    sup_flag = models.BooleanField(
        verbose_name='入荷フラグ',
        default=False,
    )
    rental_flag = models.BooleanField(
        verbose_name='レンタルフラグ',
        default=False,
    )
    return_flag = models.BooleanField(
        verbose_name='返却フラグ',
        default=False,
    )

    def __str__(self):
        return self.user


# 仕入れ先
class Supplier(models.Model):
    name = models.CharField(
        verbose_name='仕入れ先名',
        max_length=50,
    )

    def __str__(self):
        return self.name


# 入荷情報
class Stock(models.Model):
    book = models.ForeignKey(
        Book, on_delete=models.CASCADE,
        verbose_name='ISBN',
        null=True, blank=True,
    )
    buy_date = models.DateTimeField(
        verbose_name='入荷日',
        null=True, blank=True,
    )
    quantity = models.IntegerField(
        verbose_name='入荷数',
        default=0,
    )
    shop = models.ForeignKey(
        Supplier, on_delete=models.CASCADE,
        verbose_name='仕入れ先',
        null=True, blank=True,
    )
    name = models.CharField(
        verbose_name='担当者',
        max_length=50,
    )

    def save(self, *args, **kwargs):
        # 現在の在庫数に追加する
        b = Book.objects.get(isbn=self.book)
        b_q = b.book_q
        change = self.quantity
        now_q = b_q + change

        # 保存する
        b.book_q = now_q
        b.save()

        self.buy_date = now_time
        super(Stock, self).save(*args, **kwargs)

        # 履歴に追加
        BookHistory.objects.create(change=change, book=b, date=self.buy_date, user=self.name, sup_flag=True)

    def __int__(self):
        return self.quantity


# 貸し出し情報
class Rental(models.Model):
    book = models.ForeignKey(
        Book, on_delete=models.CASCADE,
        verbose_name='ISBN',
        null=True, blank=True,
    )
    user = models.CharField(
        verbose_name='貸出者名',
        max_length=50,
    )
    start_datetime = models.DateTimeField(
        verbose_name='貸出日',
        null=True, blank=True,
    )
    end_datetime = models.DateTimeField(
        verbose_name='返却日',
        null=True, blank=True,
    )
    return_flag = models.BooleanField(
        verbose_name='返却フラグ',
        default=False,
    )
    late_flag = models.BooleanField(
        verbose_name='延滞フラグ',
        default=False,
    )

    def save(self, *args, **kwargs):
        # 貸し出し情報から返却情報を取得
        r = self.return_flag

        # もし返却フラグがついていたら
        if r:
            # 在庫数から貸し出し分を増やす
            b = Book.objects.get(isbn=self.book)
            b_q = b.book_q
            change = 1
            ch_couunt = b_q + change
            b.book_q = ch_couunt
            b.book_q = ch_couunt
            # 保存する
            b.save()

            self.return_flag = True
            self.end_datetime = now_time
            super(Rental, self).save(*args, **kwargs)

            # 履歴に追加
            BookHistory.objects.create(change=change, book=b, date=now_time, user=self.user, return_flag=True)


        else:
            # 在庫数から貸し出し分を減らす
            b = Book.objects.get(isbn=self.book)
            b_q = b.book_q
            change = -1
            ch_couunt = b_q + change
            b.book_q = ch_couunt

            # 保存する
            b.save()

            self.start_datetime = now_time
            super(Rental, self).save(*args, **kwargs)

            # 履歴に追加
            BookHistory.objects.create(change=change, book=b, date=self.start_datetime, user=self.user,
                                       rental_flag=True)

    def __str__(self):
        return self.user


class Reserve(models.Model):
    book = models.ForeignKey(
        Book, on_delete=models.CASCADE,
        verbose_name='ISBN',
        null=True, blank=True,
    )
    user = models.CharField(
        verbose_name='予約者名',
        max_length=50,
    )
    start_datetime = models.DateTimeField(
        verbose_name='予約日',
        null=True, blank=True,
    )
    end_datetime = models.DateTimeField(
        verbose_name='予約完了日',
        null=True, blank=True,
    )
    reserve_flag = models.BooleanField(
        verbose_name='予約完了フラグ',
        default=False,
    )

    def save(self, *args, **kwargs):
        # 本の在庫数取得
        b = Book.objects.get(isbn=self.book)
        b_q = b.book_q
        # 現在時刻取得

        if self.reserve_flag:
            self.end_datetime = now_time
            Rental.objects.create(book=b, user=self.user, start_datetime=now_time)
        else:
            if b_q > 0:
                raise ValueError("在庫あるよー")
            self.start_datetime = now_time

templates/libr/check.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div>

        {% if book == None %}
            <div class="fw-bold fs-4 bg-gradientp-2 p-3 mb-3"  style="background: #FF97C2">API取得できませんでした。。。</div>
        {% else %}
            <div class="fw-bold fs-4 bg-gradientp-2 p-3 mb-3" style="background: #66FF99">API取得できました！</div>
        {% endif %}

            <div>
            <textarea style="width: 100%; height: 500px">{{ book }}</textarea>


            </div>
        </div>
<div style="margin-top:30px"><a class="btn btn-secondary" href="{% url 'app:index' %}" role="button">戻る</a></div>

{% endblock content %}

templates/libr/detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <h2>{{ book.title }}</h2>
    <div class="row mt-3">
        <div class="col-6">
            <img class="" style="width:80%" src={{ book.save_image.url }} alt="">
        </div>
        <div class="col-6">
            <div>書籍名：{{ book.title }}</div>
            <div>書籍名ヨミ{{ book.title2 }}</div>
            <div>ISBNコード：{{ book.isbn }}</div>
            <div>著者名：{{ book.name }}</div>
            <div>著者紹介：{{ book.name.a_detail }}</div>
            <div>出版社：{{ book.publisher_name }}</div>
            <div>在庫数：{{ book.book_q }}</div>
            <div>ページ数：{{ book.page }}</div>
            <div>予約者数：{{ reserve_list | length }}</div>
            <div>予約者数：{{ book.reserve_set.reverve_flag | length }}</div>


        </div>
    </div>
    <div class="row mt-5">
        <div class="col-6">
            <h3>貸し出しリスト</h3>
            {% for ren in renting %}
                <div>{{ ren.user }}</div>
            {% endfor %}
        </div>
        <div class="col-6">
            <h3>予約者リスト</h3>
            {% for r in reserve_list %}
                <div>{{ r.user }}</div>
            {% endfor %}
        </div>
    </div>
    <div style="margin-top:30px"><a class="btn btn-secondary" href="{% url 'app:index' %}" role="button">戻る</a></div>
    <div class="mt-5 mb-3">
        <h3>作業</h3>
        {#  フォームーム#}
        <div>
            <form action="{% url 'app:detail' book.pk %}" method="POST">

                {% csrf_token %}
                <input type="hidden" value="{{ user.get_username }}" name="user">
                <input type="hidden" value="{{ book.isbn }}" name="book">
                {#    入荷の時#}
                <div class="row">
                    <div class="col-6">
                        <h4>貸し出し or 予約</h4>
                        {#    在庫予約者数より多ければレンタル、少なければ予約#}
                        {% if rental_check > 0 %}
                            <input class="btn btn-secondary" type="submit" value="レンタル" name="action">
                        {% else %}
                            <input class="btn btn-secondary" type="submit" value="予約" name="action">
                        {% endif %}
                    </div>
                    <div class="col-6">
                        <h4>仕入れ</h4>
                        <select name="shops">
                            {% for shop in shops %}
                                <option value="{{ shop.pk }}">{{ shop.name }}</option>
                            {% endfor %}
                        </select>
                        <input type="number" min="1" name="stock" placeholder="仕入れ数">
                        <input class="btn btn-secondary" type="submit" value="入荷" name="action">
                    </div>
                </div>
            </form>
        </div>
    </div>
    {% for re in book.rental_set.all|dictsort:"start_datetime" %}
        {% if not re.return_flag %}
        <p>{{ re | length }}</p>
        {% endif %}
    {% endfor %}
{% endblock content %}

templates/libr/form.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div>
        <form method="post">
            {% csrf_token %}
            {% for field in form %}
                <div class="row form-group">
                <label class="col-4 mt-2">{{ field.label }}{{ field.errors }}</label>
                    <div class="col-8 mt-2">
                        {{ field }}
                    </div>
                {% if field.help_text %}
                <small class="text-primary">※{{ field.help_text }}</small>
                {% endif %}
                </div>
            {% endfor %}
            <button type="submit">送信</button>
        </form>

    </div>
     <div style="margin-top:30px"><a class="btn btn-secondary" href="{% url 'app:mypage' %}" role="button">戻る</a></div>
    </div>


{% endblock content %}

templates/libr/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="row">
        {% for article in object_list %}
            <div class="col-sm-4 my-3">
                <div class="card">
                    <img src="{{ article.save_image.url }}" class="card-img-top">
                    <div class="card-body align-items-end">
                        <a href="{% url 'app:detail' article.pk %}"><h5 class="card-title">{{ article.title }}</h5></a>
                        <p class="card-text">{{ article.name }}<br>{{ article.isbm }}</p>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock content %}

templates/libr/mypage.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    {% if messages %}
        <div class="messages">
            {% for message in messages %}
                <p{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
            {% endfor %}
        </div>
    {% endif %}
    <h2>{{ mypk.username }}さん</h2>
    <div class="mt-5">
        <h3>ユーザー情報</h3>
        <dl class="row">
            <dt class="col-2">ID</dt>
            <dd class="col-10">{{ mypk.pk }}</dd>
            <dt class="col-2">役割</dt>
            <dd class="col-10">
                {% if mypk.is_superuser == True %}
                    {{ "管理者" }}
                {% else %}
                    {{ "ユーザー" }}
                {% endif %}
            </dd>
        </dl>
    </div>

    <div class="mt-5">
    {% if rental_over %}
        <h3 style="color:red">返却期限の切れている本一覧</h3>
        <table class="table mb-5">
            <thead>
            <tr>
                <th></th>
                <th>図書名</th>
                <th>借りた日</th>
                <th>返却</th>
            </tr>
            </thead>
            <tbody>
            {% for ren in rental_over %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td><a href="{% url 'app:detail' ren.book.pk %}">{{ ren.book.title }}</a></td>
                    <td>{{ ren.start_datetime }}</td>
                    <td>
                        <form action="{% url 'app:mypage' %}" method="POST">{% csrf_token %}
                            <input class="submit" type="submit" value="返却">
                            <input type="hidden" value="{{ ren.pk }}" name="return">
                        </form>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% endif %}
        <h3>借りている本一覧</h3>
        <table class="table mb-3">
            <thead>
            <tr>
                <th></th>
                <th>図書名</th>
                <th>借りた日</th>
                <th>返却</th>
            </tr>
            </thead>
            <tbody>

            {% for r in rentals %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td><a href="{% url 'app:detail' r.book.pk %}">{{ r.book.title }}</a></td>
                    <td>{{ r.start_datetime }}</td>
                    <td>
                        <form action="{% url 'app:mypage' %}" method="POST">{% csrf_token %}
                            <input class="submit" type="submit" value="返却">
                            <input type="hidden" value="{{ r.pk }}" name="return">
                        </form>
                    </td>
                </tr>
            {% endfor %}
            </tbody>

        </table>
    <div>
        <button onclick="location.href={% url 'app:inquiry' %}">お問合せ</button>
    </div>
    </div>
    {#    <div class="mt-5 mb-3">#}
    {#        <h2>レンタル履歴</h2>#}
    {#     <div class="row mt-5">#}
    {#        <div class="col-6">#}
    {#            <h3>貸し出し履歴</h3>#}
    {#            {% for ren in renting %}#}
    {#                <div>{{ ren.user }}</div>#}
    {#            {% endfor %}#}
    {#        </div>#}
    {#        <div class="col-6">#}
    {#            <h3>予約者リスト</h3>#}
    {#            {% for r in reserve_list %}#}
    {#                <div>{{ r.user }}</div>#}
    {#            {% endfor %}#}
    {#        </div>#}
    {#    </div>#}


{% endblock content %}